from matplotlib.colors import ListedColormap

# Definir 42 colores distintos para cada etiqueta
colors = [
    "#000000",  # 0 - Out of border (Negro)
    "#7FFF00",  # 1 - Herbaceous crops (Verde claro)
    "#D2691E",  # 2 - Orchard, plant nurseries and forced cultivation (Marrón)
    "#8B0000",  # 3 - Vineyards (Rojo oscuro)
    "#FF4500",  # 4 - Olive groves (Naranja fuerte)
    "#FFD700",  # 5 - Other woody crops (Amarillo)
    "#ADFF2F",  # 6 - Crops in transformation (Verde lima)
    "#006400",  # 7 - Dense coniferous forests (Verde oscuro)
    "#556B2F",  # 8 - Dense deciduous forests (Oliva oscuro)
    "#8FBC8F",  # 9 - Dense forests of sclerophylls (Verde musgo)
    "#A52A2A",  # 10 - Scrub (Marrón tierra)
    "#2E8B57",  # 11 - Clear coniferous forests (Verde marino)
    "#32CD32",  # 12 - Clear deciduous forests (Verde lima)
    "#228B22",  # 13 - Clear forests of sclerophylls (Verde bosque)
    "#98FB98",  # 14 - Meadows and grasslands (Verde pastel)
    "#00CED1",  # 15 - Shore forest (Turquesa oscuro)
    "#8B4513",  # 16 - Bare forest soil (Marrón cuero)
    "#B22222",  # 17 - Burned areas (Rojo fuego)
    "#808080",  # 18 - Rocky (Gris medio)
    "#D3D3D3",  # 19 - Beaches (Gris claro)
    "#00FA9A",  # 20 - Wetlands (Verde menta)
    "#DC143C",  # 21 - Urban area (Carmesí)
    "#FF69B4",  # 22 - "Eixample" (Rosa fuerte)
    "#FFB6C1",  # 23 - Lax Urban Areas (Rosa claro)
    "#C71585",  # 24 - Isolated buildings in rural areas (Violeta oscuro)
    "#DA70D6",  # 25 - Isolated residential areas (Orquídea)
    "#0066FF",  # 26 - Green areas (Azul fuerte)
    "#8A2BE2",  # 27 - Industrial or commercial (Azul violeta)
    "#7B68EE",  # 28 - Sports and leisure areas (Azul pizarra)
    "#708090",  # 29 - Mining or landfills (Gris azulado)
    "#778899",  # 30 - Areas in transformation (Gris pálido)
    "#0000FF",  # 31 - Road network (Azul)
    "#4682B4",  # 32 - Urban bare ground (Azul acero)
    "#191970",  # 33 - Airport areas (Azul medianoche)
    "#00FFFF",  # 34 - Railway network (Cian)
    "#1E90FF",  # 35 - Port areas (Azul dodger)
    "#20B2AA",  # 36 - Reservoirs (Verde azulado)
    "#5F9EA0",  # 37 - Lakes and lagoons (Azul cadete)
    "#40E0D0",  # 38 - Watercourses (Turquesa)
    "#4682B4",  # 39 - Rafts (Azul acero)
    "#00BFFF",  # 40 - Artificial channels (Azul profundo)
    "#000080",  # 41 - Sea (Azul marino) <- Esta puedes excluirla si no quieres que el modelo la use
]

# Crear el colormap
land_cover_cmap = ListedColormap(colors)